name: Prueba de CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Chekout Repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm install
      - name: Run Linter
        run: pnpm lint
      - name: Run Tests
        run: pnpm test
